apiVersion: v1
kind: Namespace
metadata:
  name: tp-devops-namespace
  labels:
    name: tp-devops-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-devops-deployment
  namespace: tp-devops-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tp-devops
  template:
    metadata:
      labels:
        app: tp-devops
    spec:
      containers:
      - name: tp-devops
        image: blorgue/tp-devops:1.0.0
        ports:
        - containerPort: 80    
---
apiVersion: v1
kind: Service
metadata:
  name: tp-devops-service
  namespace: tp-devops-namespace
spec:
  type: NodePort
  selector:
    app: tp-devops
  ports:
    - name: http
      port: 8080
      targetPort: 80
      nodePort: 30000
