apiVersion: v1
kind: Namespace
metadata:
  name: tp-devops-namespace
  labels:
    name: tp-devops-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-devops-deployment
  namespace: tp-devops-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tp-devops
  template:
    metadata:
      labels:
        app: tp-devops
    spec:
      containers:
      - name: tp-devops
        image: blorgue/tp-devops:1.0.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tp-devops-service
  namespace: tp-devops-namespace
spec:
  type: NodePort
  selector:
    app: tp-devops
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-secret: my-tls-secret
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  name: tp-devops-ingress
  namespace: tp-devops-namespace
spec:
  tls:
  - hosts:
    - www.tp-devops.com
    secretName: my-tls-secret
  rules:
    - host: www.tp-devops.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend: 
              service:  
                name: tp-devops-service
                port:
                  name: http
