apiVersion: v1
kind: Namespace
metadata:
  name: tp-devops-namespace
  labels:
    name: tp-devops-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tp-devops-deployment
  namespace: tp-devops-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tp-devops
  template:
    metadata:
      labels:
        app: tp-devops
    spec:
      containers:
      - name: tp-devops
        image: blorgue/tp-devops:1.0.0
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tp-devops-service
  namespace: tp-devops-namespace
spec:
  type: NodePort
  selector:
    app: tp-devops
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tp-devops-ingress
  namespace: tp-devops-namespace
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend: 
              service:  
                name: tp-devops-service
                port:
                  number: 8080
