name: Check formatting with Prettier

on:
  pull_request:
    branches: [main]

jobs:
  check-formatting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Check formatting
        run: |
            chmod +x ./node_modules/.bin/prettier
            npx prettier --check .pretierrc.json --parser json

      - name: Upload checkstyle report
        uses: actions/upload-artifact@v2
        with:
          name: checkstyle
          path: checkstyle.xml
